#!/usr/bin/bash
#this is an exercise using while loops and elif statements
i=1
while [ $1 -eq 11 ]
do 
	i=$((i+1))
	if [ $1 -eq 4 ]
	then 
		echo "bad luck" 
	else 
		echo "Best School" 
	fi 
	if [ $1 -eq 8 ]
	then 
		echo "good luck"
	else 
		echo "Best School" 
	fi
	i=$((i+1))
done  
