#!/usr/bin/env bash
#this is an exercise to use the case statement
i=1
while [ $i -le 20 ] 
do 
	case $i in
		4) 	echo "$i"
			echo "bad luck from China";;
		9) 	echo "$i"
			echo "bad luck from Japan";;
			
		17) 	echo "$i"
			echo "bad luck from Italy";;
	       	*) echo "$i";;	
	esac
 i=$((i+1))
done 
