#!/usr/bin/env bash
#this is working on if statements

if [ -e school ]
then 
	echo "school file exists"
	if [ -z "" ] 
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi 
	if [ -f school ]
	then
		echo "school is a regular file"
	
	fi
else 
	echo "school file does not exist"
fi
